version: '3.8'

services:
  app:
    build: ./
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      # سایر متغیرهای محیطی...
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my_password
      MYSQL_DATABASE: my_database
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
